---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      path: /mnt/c/Users/sruja/OneDrive/Desktop/Project/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAMdViWyAYcmpcolPqmcGn4IwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUxMjMxMDkyNDAwWhcNMzUxMjI5MDkyNDAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BIyaqjKsDx+v8FgE+8Y1GejBAglo4fbeXVSDwERLCusq95b9FQ3e2dpYQZ5cFfq9
          q/kARlhBT2ZWmT2An1qIvPOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          PyOva5p6EAYsHfn10cXOL8yLJa9wKLG5lqb0pmxirgMwCgYIKoZIzj0EAwIDRwAw
          RAIgBFwiMYuTylwjRGEQeyL8JKSXz7Sooa8eLQ+8Oj6LaKUCIEjtc7vZQSur2MFn
          elQHVS48CBtPei3HW33egVFKBggY
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
